### ISSUE TITLE
Use with Web Workers?

### ISSUE THREAD

**Issue by khchan** [geut/moleculer-browser#1]
Thanks for the awesome lib! I was trying to use this with web workers but I get an error:
```
Uncaught ReferenceError: window is not defined
  at process.js:13
  at index.js:468
```
Is it possible to add support for other globals like self?

**Comment by tinchoz49** [comment]
Hey @khchan thank you! I think that window.process shouldn't be there :smile: . Can you try the new version?

**Comment by khchan** [comment]
Thanks @tinchoz49! that's working swimmingly now.
